{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(user_active_users_total{pizza=\"active_users\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_total{method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_request_total{method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_request_total{method=\"DELETE\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_request_total{pizza=\"total\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_percentage{source=\"jwt-pizza-service\", pizza=\"memory_usage\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_cpu_usage_percentage{pizza=\"cpu_usage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_auth_attempts_successful{pizza=\"successful_auth\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(auth_auth_attempts_failed{pizza=\"failed_auth\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(purchase_pizzas_sold_total{pizza=\"sold_total\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(purchase_creation_failures_total{pizza=\"creation_failures\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "user_request_latency_average{pizza=\"latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(purchase_revenue_total{pizza=\"revenue_total\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "purchase_creation_latency_average{pizza=\"creation_latency\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}